routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});
Route::get('/history', function () {
    return view('history');
})->name('history')->middleware('auth');


Route::resources([ 
    'criteria' => 'CriteriaController',
    'alternative' => 'AlternativeController',
    'criteria-value' => 'CriteriaValueController', 
    'alternative-value' => 'AlternativeValueController', 
    'user' => 'UserController',
    'test' => 'TestController',
    'preferences' => 'PreferencesController',
    'count' => 'CountController'
    ]);

Route::post('/criteria-test/{test}', 'CriteriaController@critest')->name('criteria-test');
Route::get('/user-register', 'UserController@register')->name('user-register');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/home/goal', 'HomeController@manageGoal')->name('manage-goal');

Route::get('/getCriteriaWeight', 'CriteriaValueController@getCriteriaWeight')->name('getCriteriaWeight');
Route::get('/getAlternativeWeight/{criteria_id}', 'AlternativeValueController@getAlternativeWeight')->name('getAlternativeWeight');

Route::get('/user-page', 'UserController@getUsers')->name('user-page')->middleware('auth');

resources/views/alt-form.blade.php
<div class="modal-header">						
    <h4 id="alternative-modal-title" class="modal-title">Add Alternative</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>
<div class="modal-body">					
    <div class="form-group">
        <label>Alternative Name</label>
        <input type="text" class="form-control" name="name" id="alt_name" required>
    </div>
    <div class="form-group">
        <label>Alternative Information</label>
        <textarea type="text" class="form-control" name="info" id="alt_info" rows="3" required></textarea>
    </div>
    <div class="form-group">
        <input type="hidden" class="form-control" name="action" id="alternative-action" value="add">
        <input type="hidden" class="form-control" name="alt_id" id="alt_id">
        <input type="hidden" class="form-control" name="user_id" value="{{ Auth::user()->id }}">
    </div>					
</div>

resources/views/alternative-details.blade.php
@extends('main-template', [
  'title' => 'Details', 
  'activePage' => 'alternative-details',
  'activeChild' => 'none'
  ])
@section('content')
  <div class="card-details mt-3">
    <span class="label-details">Name :</span>  
    <div class="ml-4">
      <div class="card">
        <div class="card-body p-2">
          <p class="alternative-name">{{$data->alternative['name']}}</p>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-details">
    <span class="label-details">Informations :</span>  
    <div class="ml-4">
      <div class="card">
        <div class="card-body p-2">
          <p>{{$data->alternative['info']}}</p>
        </div>
      </div>
    </div>
  </div>
  <hr class="m-0">
  <div class="card-details">
    <span class="label-details">Comments :</span>
    <div class="ml-4">
      @if(count($data->comments) < 1)
      <div id="no-comments" class="card text-center">
        No Comments.
      </div>
      @endif
      @foreach($data->comments as $c)
      <div class="card">
        <div class="card-body p-2">
          <label class="comment-label" for="cm">{{$c->user}}</label>
          <p>{{$c->comment}}</p>
          <div class="float-right">{{date('d M Y H:i:s', $c->comment_date)}}</div><br>
        </div>
      </div>
      @endforeach
    </div>

  </div>
@endsection

resources/views/alternative-value.blade.php
@extends('main-template', [
  'title' => 'Alternative value', 
  'activePage'=>'alternative', 
  'activeChild'=>'cc-alternative'
  ])
@section('content')
  <nav id="nav-alternative">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      @foreach($data as $d)
        <a class="nav-item nav-link" id="nav-{{$d['criteria_id']}}-tab" data-toggle="tab" href="#nav-{{$d['criteria_id']}}" 
        role="tab" aria-controls="nav-{{$d['criteria_id']}}" aria-selected="true">
        {{$d['criteria_name']}}</a>
      @endforeach
      <a class="nav-item nav-link" id="nav-sentiment-tab" data-toggle="tab" href="#nav-sentiment" 
        role="tab" aria-controls="nav-sentiment" aria-selected="true">
        Sentiment Score  
      </a>
    </div>
  </nav>
  <br>
  <div class="tab-content" id="nav-tabContent">
    @foreach($data as $d)
      <div class="tab-pane fade" id="nav-{{$d['criteria_id']}}" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="table-wrapper">
          <div class="table-title">
            <div class="d-flex">
              <div class="mr-auto p-2">
                <h2><b>Comparison</b> Value</h2>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped table-hover table-text-center long-table">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Alernative</th>
                  <th>Comparison Alternative</th>
                  <th>Value</th>
                  <th>Actions</th>
                </tr>
              </thead>

              <tbody>
                @foreach($d['data'] as $c)
                  <tr id="av-row-{{$c->id}}" data-href="linknya">
                    <td></td>
                    <td>{{$c->altern_name}}</td>
                    <td>{{$c->altern_name_compared}}</td>
                    <td>{{$c->value}}</td>
                    <td>
                        <a href="#" class="edit" 
                          data-id="{{$c->id}}" data-altern="{{$c->altern_name}}" 
                          data-altern_comp="{{$c->altern_name_compared}}" data-c_name="{{$d['criteria_name']}}"
                          data-value="{{$c->value}}" data-toggle="modal" data-target="#alternative_value_modal"
                          data-criteria="{{$d['criteria_id']}}">
                          <i class="material-icons" data-toggle="tooltip">&#xE254;</i>
                        </a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>

        <div class="table-wrapper">
          <div class="table-title">
            <div class="d-flex">
              <div class="mr-auto p-2">
                <h2><b>Alternative Weight</b> Data</h2>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table id="aw-table-{{$d['criteria_id']}}" class="table table-striped table-hover table-text-center">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Altenative</th>
                  <th>Weight</th>
                </tr>
              </thead>
              <tbody>
                @foreach($d['weight'] as $w)
                <tr>
                    <td></td>
                    <td>{{$w['alternative_name']}}</td>
                    <td>{{$w['weight']}}</td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>  
          
        </div>
      </div>
    @endforeach
    <div class="tab-pane fade" id="nav-sentiment" role="tabpanel" aria-labelledby="nav-sentiment-tab">
      <div class="table-wrapper">
        <div class="table-title">
          <div class="d-flex">
            <div class="mr-auto p-2">
              <h2><b>Sentiment Analysis</b> Score</h2>
            </div>
            <!-- <div class="ml-auto p-2">
              <i class="material-icons">refresh</i>
            </div> -->
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-hover table-text-center">
            <thead>
              <tr>
                <th>No.</th>
                <th>Altenative</th>
                <th>Weight</th>
              </tr>
            </thead>
            <tbody>
              @foreach($sentimentWeight as $w)
              <tr>
                  <td></td>
                  <td>{{$w['alternative_name']}}</td>
                  <td>{{$w['score']}}</td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/alternative.blade.php
@extends('main-template', [
  'title' => 'Data alternative', 
  'activePage'=>'alternative', 
  'activeChild'=>'cd-alternative'
  ])
@section('content')
  <div class="table-wrapper">
    <div class="table-title">
      <div class="d-flex">
        <div class="mr-auto p-2">
          <h2><b>Alternative</b> Data</h2>
        </div>
        <div class="ml-auto p-2">
          <a href="#add_alternative_modal" class="btn btn-success" data-action="add"
            data-toggle="modal">
              <i class="material-icons">&#xE147;</i> 
              <span class="span-add">Add New Alternative</span>
          </a>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table id="alternative-table" class="table table-striped table-hover table-text-center long-table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Name</th>
            <!-- <th>Information</th> -->
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            @foreach($data as $d)
              <tr id="a-row-{{$d->id}}" class="clickable-row">
                  <td></td>
                  <td><a href="{{route('alternative.show', $d->id)}}">{{$d->name}}</a></td>
                  <!-- <td>{{$d->info}}</td> -->
                  <td>
                      <a href="#" class="edit" data-action="edit" data-id="{{$d->id}}" data-name="{{$d->name}}" 
                        data-info="{{$d->info}}" data-toggle="modal" data-target="#edit_alternative_modal">
                        <i class="material-icons" data-toggle="tooltip">&#xE254;</i>
                      </a>
                      <a href="#delete_modal" class="delete" data-toggle="modal" data-id="{{$d->id}}">
                        <i class="material-icons" data-toggle="tooltip">&#xE872;</i>
                      </a>
                  </td>
              </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/criteria-value.blade.php
@extends('main-template', [
  'title' => 'Criteria Value', 
  'activePage'=>'criteria',
  'activeChild'=>'cc-criteria'
  ])
@section('content')
  <div class="table-wrapper">
    <div class="table-title">
      <div class="d-flex">
        <div class="mr-auto p-2">
          <h2><b>Criteria Value</b> Data</h2>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-hover table-text-center long-table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Criteria</th>
            <th>Comparison Criteria</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          @foreach($data as $d)
          <tr id="cv-row-{{$d->id}}">
              <td></td>
              <td>{{$d->c_name}}</td>
              <td>{{$d->c_name_compared}}</td>
              <td>{{$d->value}}</td>
              <td>
                  <a href="#" class="edit" 
                    data-id="{{$d->id}}" data-c="{{$d->c_name}}" data-c_comp="{{$d->c_name_compared}}"
                    data-value="{{$d->value}}" data-toggle="modal" data-target="#criteria_value_modal">
                    <i class="material-icons" data-toggle="tooltip">&#xE254;</i>
                  </a>
              </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>

  <input type="hidden" id="cr-criteria" value="{{$CR}}">
  <div class="alert cr-criteria" role="alert">
    Consistency ratio : <span class="cr-value">{{$CR}}</span>
  </div>

  <div class="table-wrapper">
    <div class="table-title">
      <div class="d-flex">
        <div class="mr-auto p-2">
          <h2><b>Criteria Weight</b> Data</h2>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table id="criteria-weight-table" class="table table-striped table-hover table-text-center">
        <thead>
          <tr>
            <th>No.</th>
            <th>Criteria</th>
            <th>Weight</th>
          </tr>
        </thead>
        <tbody>
          @foreach($weight as $w)
          <tr>
              <td></td>
              <td>{{$w['criteria_name']}}</td>
              <td>{{$w['weight']}}</td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    
  </div>
@endsection

resources/views/criteria.blade.php
@extends('main-template', [
  'title' => 'Criteria', 
  'activePage'=>'criteria',
  'activeChild'=>'cd-criteria'
  ])
@section('content')

  <div class="table-wrapper">
    <div class="table-title">
        <div class="d-flex">
            <div class="mr-auto p-2">
              <h2><b>Criteria</b> Data</h2>
            </div>
            <div class="ml-auto p-2">
              <a id="add_criteria" href="#add_criteria_modal" class="btn btn-success" data-toggle="modal">
                <i class="material-icons">&#xE147;</i> 
                <span class="span-add" >Add New Criteria</span>
              </a>  
            </div>
        </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-hover table-text-center" id="table-criteria">
          <thead>
              <tr>
                  <th>No.</th>
                  <th>Criteria</th>
                  <th>Actions</th>
              </tr>
          </thead>
          <tbody>
              @foreach($data as $d)
              <tr id="row-{{$d->id}}">
                  <td></td>
                  <td>{{$d->criteria_name}}</td>
                  @if($d->criteria_type != 3)
                    <td>
                        <a href="#" class="edit" 
                          data-id="{{$d->id}}" data-name="{{$d->criteria_name}}" data-toggle="modal" data-target="#edit_criteria_modal">
                          <i class="material-icons" data-toggle="tooltip">&#xE254;</i>
                        </a>
                        <a href="#delete_modal" class="delete" data-toggle="modal" data-id="{{$d->id}}">
                          <i class="material-icons" data-toggle="tooltip">&#xE872;</i>
                        </a>
                    </td>
                  @else
                    <td> - </td>
                  @endif
              </tr>
              @endforeach
          </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/history.blade.php
@extends('main-template', [
  'title' => 'History', 
  'activePage' => 'history',
  'activeChild' => 'none'
])
@section('content')
  <div class="dashboard-goal">
    <span>Goal :</span>
    <h3 class="goal-cal">{{Session::get('goal')}}</h3>
  </div>
  <div class="table-wrapper">
    <div class="table-title">
      <div class="d-flex">
        <div class="mr-auto p-2">
          <h2><b>Histories</b></h2>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-hover table-text-center">
        <thead>
          <tr>
            <th>Ranking</th>
            <th>Alternative</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          @if(Session::has('history'))
            @foreach(Session::get('history') as $d)
            <tr>
                <td></td>
                <td> <a href="{{route('alternative.show', $d->id)}}">{{$d->name}}</a></td>
                <td>{{$d->score}}</td>
            </tr>
            @endforeach
          @endif
        </tbody>
      </table>
    </div>
   
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/main2.blade.php
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Sycom Corp</title>

        <!-- Bootstrap CSS CDN -->
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="{{ asset('css') }}/bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="{{ asset('css') }}/bootstrap/awesome-bootstrap-checkbox.css">
        <link rel="stylesheet" href="{{ asset('main') }}/css/googleapis.css">
        <link rel="stylesheet" href="{{ asset('main') }}/css/googleapis-material-icon.css">
        <link rel="stylesheet" href="{{ asset('main') }}/css/font-awesome.min.css?v=3.2.1">
        <link rel="stylesheet" href="{{ asset('main') }}/css/bootstrap.css">
        <link rel="stylesheet" href="{{ asset('main') }}/css/dataTables.bootstrap4.min.css">
            <!-- Compiled and minified CSS -->

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{{ asset('css') }}/custom_style.css">
    </head>

    <body onload="myFunction()">
        <div class="btn" onclick="topFunction()" id="btn-top">
            <b>Top</b>
        </div>
        <div id="loader"></div>
        @include('sidebar') 

        <script defer src="{{ asset('main') }}/js/jquery.min.js"></script>
        <script defer src="{{ asset('main') }}/js/jquerysession.js"></script>

        <!-- dataTables -->
        <script defer src="{{ asset('main') }}/js/jquery-3.3.1.js"></script>
        <script defer src="{{ asset('main') }}/js/jquery.dataTables.min.js"></script>
        <script defer src="{{ asset('main') }}/js/dataTables.bootstrap4.min.js"></script>

        <script src="{{ asset('main') }}/js/jquery-3.3.1.slim.min.js"></script>
        <script src="{{ asset('main') }}/js/popper.min.js"></script>
        <script defer src="{{ asset('main') }}/js/solid.js"></script>
        <script defer src="{{ asset('main') }}/js/fontawesome.js"></script>
        <script src="{{ asset('main') }}/js/bootstrap.min.js"></script>

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <script>
            var activePage = "<?= $activePage ?>";
        </script>
        
        <!-- custom js -->
        <script src="{{ asset('main') }}/js/app.js"></script>
        <script src="{{ asset('main') }}/js/custom.js"></script>
    </body>
</html>

resources/views/sidebar.blade.php
<div id="myDiv" class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h4>Sycom Corp.</h4>
            <h6>Hai, {{Auth::user()->username}}!</h6>
        </div>
        <ul class="list-unstyled components">
            <!-- <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    <li>
                        <a href="#">Home 1</a>
                    </li>
                    <li>
                        <a href="#">Home 2</a>
                    </li>
                    <li>
                        <a href="#">Home 3</a>
                    </li>
                </ul>
            </li> -->
            <li id="home">
                <a href="{{ route('home') }}">Home</a>
            </li>
            <li id="criteria">
                <a href="{{ route('criteria.index') }}">Criteria</a>
            </li>
            <li id="criteria_value">
                <a href="{{ route('criteria-value.index') }}">Criteria Value</a>
            </li>
            <li id="alternative">
                <a href="{{ route('alternative.index') }}">Alternative</a>
            </li>
            <li id="alternative_value">
                <a href="{{ route('alternative-value.index') }}">Alternative Value</a>
            </li>
            <li id="calculation">
                <a href="{{ route('count.index') }}">Calculation</a>
            </li>
        </ul>
        <button class="btn btn-danger btn-logout" 
            onclick="
                event.preventDefault();
                document.getElementById('logout-form').submit();
            ">
            <a href="{{ route('logout') }}">
                <i class="fas fa-sign-out-alt"></i>
                {{ __('Logout') }}
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </button>
    </nav>

    <!-- Page Content -->
    <div id="content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
                <h1 class="navbar-text" >{{$title}} |</h1>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="main">
                <div class="container">
                    <div class="alert alert-dismissible fade show" role="alert" id="alert-criteria">
                        <div id="alert-message">ddd</div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @if(Session::has('alert'))
                        <div class="alert alert-danger alert-dismissible fade show alert-global" role="alert">
                            <div>{{Session::get('alert')}}</div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    @if(Session::has('alert-success'))
                        <div class="alert alert-success alert-dismissible fade show alert-global" role="alert">
                            <div>{{Session::get('alert-success')}}</div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
</div>
@include('modals')

resources/views/users.blade.php
@extends('main-template', [
  'title' => 'User', 
  'activePage'=>'manage-user',
  'activeChild'=>'none'
  ])
@section('content')

  <div class="table-wrapper">
    <div class="table-title">
        <div class="d-flex">
            <div class="mr-auto p-2">
              <h2><b>Users</b> Data</h2>
            </div>
            <div class="ml-auto p-2">
              <a id="add-user" href="#" class="btn btn-success" data-toggle="modal" data-target="#manage-users" >
                <i class="material-icons">&#xE147;</i> 
                <span class="span-add" >Add User</span>
              </a>  
            </div>
        </div>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-hover table-text-center" id="table-manage-users">
          <thead>
              <tr>
                  <th>No.</th>
                  <th>Name</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Password</th>
                  <th>Action</th>
              </tr>
          </thead>
          <tbody>
            @foreach($user as $u)
              <tr id="u-row-{{$u->id}}">
                  <td></td>
                  <td>{{$u->name}}</td>
                  <td>{{$u->username}}</td>
                  <td>{{$u->email}}</td>
                  <td>{{$u->password}}</td>
                  <td>
                      <a href="#" class="edit edit-user" 
                        data-id="{{$u->id}}" data-toggle="modal" data-target="#manage-users">
                        <i class="material-icons" data-toggle="tooltip">&#xE254;</i>
                      </a>
                      <a href="#delete_modal" class="delete" data-toggle="modal" data-id="{{$u->id}}">
                        <i class="material-icons" data-toggle="tooltip">&#xE872;</i>
                      </a>
                  </td>
              </tr>
            @endforeach
          </tbody>
      </table>
    </div>
  </div>
@endsection